#!/bin/bash

rm -rf /Volumes/share/roms/amiga*/.*
rm -rf /Volumes/share/roms/amiga*/media
rm /Volumes/share/roms/amiga*/*.uae
rm /Volumes/share/roms/amiga*/gamelist.*

rsync -a --no-owner --no-group --exclude='._*' --exclude='.DS_Store' \
  ./roms/ root@recalbox.local:/recalbox/share/roms/
